name: ${pluginName}
version: ${pluginVersion}
api-version: "1.21"
main: dev.mizule.mserverlinks.paper.mServerLinks
authors: [${pluginAuthor}]
loader: dev.mizule.mserverlinks.libs.xyz.jpenilla.gremlin.runtime.platformsupport.DefaultsPaperPluginLoader
bootstrapper: dev.mizule.mserverlinks.paper.mServerLinksBootstrapper
dependencies:
  server:
    PlaceholderAPI:
      required: false
      load: BEFORE
    MiniPlaceholders:
      required: false
      load: BEFORE
